### ISSUE TITLE
[ISSUE] Buttons are not working in-game.

### ISSUE THREAD

**Issue by Animeliqite** [Gatete/Mario-Worlds-Delta#2]
I've tried everything without editing the code to get through the title screen, but it didn't work. Button system seems to be the only main problem here. If you would fix it, I'd appreciate it a lot :3

I use Game Maker Studio 1.4.1804, Steam Edition btw.

**Comment by MistaDrop** [comment]
I use Game Maker 1.4.9999 and am experiencing the same issue.

**Comment by GateteVerde** [comment]
Pardon for the late reply, but this can be solved by deleting the **settings** file located at the AppData folder of the engine.
