### ISSUE TITLE
Mario stays in free fall state for all levels

### ISSUE THREAD

**Issue by GoldyFredy9** [Gatete/Mario-Worlds-Delta#5]
Regardless if i obtain a power-up, Mario stays in falling state when i enter a level and am unsure how to fix this myself. along with the ground being more pixelated than usual.
![image](https://user-images.githubusercontent.com/109116387/192222394-e12d8c73-5b45-4cc0-8783-2d774ab6779c.png)
![image](https://user-images.githubusercontent.com/109116387/192222478-92feb236-c315-4e7f-9bbb-c34d016df24f.png)

**Comment by mariocraft31** [comment]
having the same issue, i can't pinpoint what does this but i think it has something to do with gravity?

**Comment by GateteVerde** [comment]
Sorry for the late reply but this is caused by GameMaker Studio 2

You need to tick on "Collision Compatibility Mode" in the Game Options

**Comment by mariocraft31** [comment]
Thank you! As for the pixelated ground, I found that you can fix it by increasing the Texture Page Size in the Windows Settings
